# Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
nums = [10, 20, 30, 40, 50]

nums.append(60)
print("After append:", nums)

nums.extend([70, 80])
print("After extend:", nums)

nums.insert(2, 25)
print("After insert:", nums)

nums.remove(25)
print("After remove:", nums)

popped = nums.pop()
print("After pop:", nums)
print("Popped value:", popped)

copy_nums = nums.copy()
nums.clear()
print("After clear:", nums)

nums = copy_nums

idx = nums.index(30)
print("Index of 30:", idx)

count = nums.count(40)
print("Count of 40:", count)

nums.sort()
print("Sorted list:", nums)

nums.reverse()
print("Reversed list:", nums)

After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 30, 40, 50, 60, 70, 80]
After pop: [10, 20, 30, 40, 50, 60, 70]
Popped value: 80
After clear: []
Index of 30: 2
Count of 40: 1
Sorted list: [10, 20, 30, 40, 50, 60, 70]
Reversed list: [70, 60, 50, 40, 30, 20, 10]


2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [3]:
students = ('Harsha', 'Nikitha', 'Thanu')
try:
    students[1] = 'Amit'
except TypeError as e:
    print("Error:", e)

Error: 'tuple' object does not support item assignment


3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [4]:
nums_with_dupes = [1, 2, 2, 3, 4, 4, 5]
nums_set = set(nums_with_dupes)
print("Set without duplicates:", nums_set)

Set without duplicates: {1, 2, 3, 4, 5}


4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [7]:
student = {'name': 'Ravi', 'age': 21, 'city': 'Tirupati'}
print("Before Update: ", student)
student['age'] = 22
student['email'] = 'ravi@email.com'
print("After update the Final dictionary is :", student)

Before Update:  {'name': 'Ravi', 'age': 21, 'city': 'Tirupati'}
After update the Final dictionary is : {'name': 'Ravi', 'age': 22, 'city': 'Tirupati', 'email': 'ravi@email.com'}


5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [11]:
age = int(input("enter the age of voter :"))
if age >= 18:
    print("The voter is eligible to vote")
else:
        print("The voter is not elgible to vote")

The voter is eligible to vote


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [22]:
Marks = int(input("enter the marks: "))
if Marks >= 90:
    grade = "A"
elif Marks >= 75:
     grade = "B"
elif Marks >= 50:
    grade = "c"
else:
    grade = "fail"
print("The Student Grade is :",grade)

The Student Grade is : A


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [29]:
Num = int(input("Enter the number :"))
if Num > 0:
    if Num % 2 == 0:
        print(f"The given {Num} is Positive and Even.")
    else:
        print(f"The given {Num} is Positive and Odd.")
else:
    if Num == 0:
       print(f"The given {Num} is Zero.")
    else:
        print(f"The given {Num} is Not Positive.")

The given 0 is Zero.


# Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [30]:
import numpy as np

a = np.array(5)
print(a)

b = np.array([1, 2, 3, 4, 5])
print(b)

c = np.array([[10, 20, 30], [40, 50, 60]])
print(c)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [33]:
d = np.random.randint(0, 100, (4, 4))
print(d)

[[80 30 13 98]
 [44 55 56 65]
 [15 40 13 80]
 [77 28 18 95]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [35]:
import pandas as pd

e = np.random.randint(0, 100, (3, 3))
df = pd.DataFrame(e, columns=['A', 'B', 'C'])
print(df)

    A   B   C
0  66  37  95
1  20  64  84
2  56  28  56


# Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [38]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Ravi', 'Priya', 'John', 'Ana', 'Paul', 'Ravi', 'Sara', 'Tom', 'Leo', 'Anu'],
    'Age': [21, 22, 24, 21, 23, 21, 25, 22, 24, 23],
    'City': ['Tirupati', 'Delhi', 'Mumbai', 'Chennai', 'Hyderabad', 'Tirupati', 'Mumbai', 'Delhi', 'Chennai', 'Hyderabad'],
    'Salary': [50000, 52000, np.nan, 48000, 50000, 50000, 56000, np.nan, 47000, 48000]
}

df_small = pd.DataFrame(data)
print(df_small.info())
print(df_small.describe())

selected = df_small[['Name', 'City']]
print(selected)

df_small = df_small.drop(['City'], axis=1)
print(df_small)

mean_salary = df_small['Salary'].mean()
df_small['Salary'] = df_small['Salary'].fillna(mean_salary)
print(df_small)

df_small = df_small.drop_duplicates()
print(df_small)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes
None
             Age        Salary
count  10.000000      8.000000
mean   22.600000  50125.000000
std     1.429841   2850.438563
min    21.000000  47000.000000
25%    21.250000  48000.000000
50%    22.500000  50000.000000
75%    23.750000  50500.000000
max    25.000000  56000.000000
    Name       City
0   Ravi   Tirupati
1  Priya      Delhi
2   John     Mumbai
3    Ana    Chennai
4   Paul  Hyderabad
5   Ravi   Tirupati
6   Sara     Mumbai
7    Tom      Delhi
8    Leo    Chennai
9    Anu  Hyderabad
    Name  Age   Salary
0   Ravi   21  50000.0
1  Priya   22  52000.0
2   John   24      NaN
3    Ana   21 